[package]
name = "spnative"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3

[lib]
crate_type = ["cdylib"]

[dependencies]
jni = "0.21.1"
anyhow = "1.0"
log = "0.4.17"
once_cell = "1.17.0"
