name: API Check

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**.kt'
      - '**.kts'
      - '**.proto'
      - '.github/workflows/*.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.kt'
      - '**.kts'
      - '**.proto'
      - '.github/workflows/*.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: burrunan/gradle-cache-action@v1
        name: Checker
        with:
          job-id: api-checker
          arguments: apiCheck
          gradle-version: wrapper
